### ISSUE TITLE
YATCO exceeds container by 25px 

### ISSUE THREAD

**Issue by bduza** [demonnic/YATCO#11]
`    demonnic.chat.windows[tab] = Geyser.MiniConsole:new({
--      fontSize = demonnic.chat.config.fontSize,
      x = 0,
      y = 25,
      height = "100%",
      width = "100%",
      name = string.format("win%s", tab),
    }, demonnic.chat.container)`

The y pos is 25 pixels down from the top of the container, and the height is 100%, which means the miniconsoles created overshoot the bottom of the container by 25 pixels.

Fix:

`height = "-0px" 
`

**Comment by demonnic** [comment]
fixed in EMCO
