### ISSUE TITLE
Blank line between messages

### ISSUE THREAD

**Issue by Brenex** [demonnic/YATCO#9]
Just a suggestion for a configuration option to include blank lines between lines added to chat logs.

See: http://forums.achaea.com/discussion/2661/yatco-23-line-spacing-in-all-tabs

**Comment by demonnic** [comment]
Good idea, I'll try to include it with the other changes I'm looking at today.

**Comment by Brenex** [comment]
new config option: demonnic.chat.config.blankline
code to insert after copy()


  if demonnic.chat.config.blankline then
    demonnic.chat.windows[chat]:echo("\n")
    if demonnic.chat.config.Alltab then
      demonnic.chat.windows[demonnic.chat.config.Alltab]:echo("\n")
    end
  end

**Comment by demonnic** [comment]
Included in EMCO 1.1 (github.com/demonnic/EMCO)
